pull_request_rules:
  - name: Notify when a PR is removed from the queue
    description: Notify the PR author when its pull request is removed from the merge queue.
    conditions:
      - queue-dequeue-reason != none
      - queue-dequeue-reason != pr-merged
    actions:
      comment:
        message: >
          Hey @{{author}}, your pull request has been dequeued due to the
          following reason: {{queue_dequeue_reason}}.

          Sorry about that, but you can requeue the PR by using `@mergifyio
          requeue` if you think this was a mistake.
  - name: Make sure PR are almost up to date before merging
    description: This automatically updates PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions:
      - "#commits-behind >= 10"
    actions:
      update:
  - name: Label Mergify Stacks PRs
    description: Pull requests that are part of a Mergify stack should be labeled as such
    conditions:
      - "body ~= ^Change-Id:"
    actions:
      label:
        toggle:
          - stack
